sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: '8afcfef6378b78a09781953bfc447bb5e223532a'
  keep-history: true
  on:
    branch: master
  local-dir: public