# Header
menu:
  Home: /
  Archives: /archives
rss: https://github.com/learn2pro

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: 'UA-90773148-1'
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: '100023269004018'
fb_app_id:
mathjax:
   enable: true